#!/usr/bin/python3.1

import itertools


text = """IWZHKTWHLZKWXYGKPLEKQLEKGZXNGWPXOGTBHLPQGRQLEKXSRXYRLEKYISWYJHPGXXHRKGHYYHTLHJHX
HPPXEKGIYTLHTHRGEKYZRTFBGRFLJXYHRGZJZXYQHLRHRJHOZWYXYGJGZIHLRHXHKWIWHZRTPLEKHBHL
XHIHLHWRQSEKYHHWBGWOXLEKBSKPTGTZWEKHLRWHEKYQLEKIHXYFZKGPYHRGPPHLRKLHWBGWRLEKYPGH
RJHWFZXGHZQHRLEKBGWIQLEKJGRFGPPHLRRZWHLRHRQGRYHPXGENZRTTGEKXWGRFHRGZIUGENHRTLRHL
RHUSXYEKGLXHZRTJHPGRJYHKGPOGEKYZKWRGEKFBSYGGRHLRHQXEKSHRHRXYLPPHRRHOHPQSWJHRTLHS
OHWRBSPNHRXYWHLILJZRTBSPPLJTLHZRYHWRXEKBHWQLWXEKLHRHRTGXJZYHGRFHLEKHRLEKKSIIYHRG
EKHLRHQXSXEKPLQQHRXSQQHWHLRHRJZYHRKHWOXYFZJHRLHXXHRZQFBSHPILRHJHWOHLKHLXXHQXSRRH
RXEKHLRZRTRZRHWLRRHWYHLEKQLEKTGXXTLHXHWSWYTLHXHPOHUSPKSHKHKGOHBLHQHLRHAGYHWXYGTY
ZRTLEKIWHZYHQLEKBLHTHWHLRQGPOHLNPGWHQKLQQHPZRYHWTHQIZRIFLJXYHRJWGTHFZQLYYGJFZHXX
HR"""

txl = list(text)
txl.sort()

rt = []

for i,k in itertools.groupby(txl):
	tm = list(k)
	rt.append((len(tm), tm[0]))

rt.sort()

rt.remove((9, '\n'))

print(rt)
